name: Wiki Sync

on:
  push:
    branches:
      - main
      - modularize-and-refactor
    paths:
      - 'docs/wiki/**'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs/wiki/
          ignore: ""
